version: '3'
volumes:
  csv_data:
  pgdata:

services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-""}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-""}
      POSTGRES_DB: ${POSTGRES_DB:-""}
    ports:
      - "35432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - /home/lucas/Documents/openmetadata-docker/docker-etl-postgres/csv_data:/opt/csv_data
    networks:
      - openmetadata-docker_app_net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-""}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-""}
    ports:
      - "5052:80"
    depends_on:
      - db
    networks:
      - openmetadata-docker_app_net

networks:
  openmetadata-docker_app_net:
    external: true
